import { Skill, SkillCheckpoint } from '../types';
import { generateSkillQuestions } from '../api/client';

export interface AssessmentQuestion {
  id: string;
  checkpointId?: string;
  checkpointTitle: string;
  question: string;
  options: string[];
  correctIndex: number;
  explanation: string;
}

export interface AssessmentResult {
  skillId: string;
  skillName: string;
  totalQuestions: number;
  correctAnswers: number;
  scorePercentage: number;
  passed: boolean; // true if scorePercentage >= 80
  status: 'verified' | 'self-claimed';
  checkpointBreakdown: {
    checkpointTitle: string;
    passed: boolean;
    explanation: string;
  }[];
}

/**
 * Generates an AI assessment for a skill.
 * Questions are generated by the backend AI service (Google Gemini).
 * Falls back to dynamic template questions only if the AI is unavailable.
 */
export const getOrGenerateSkillAssessment = async (skill: Skill): Promise<AssessmentQuestion[]> => {
  try {
    const generated = await generateSkillQuestions(skill.name, 'Beginner', 5);
    if (generated && generated.length > 0) {
      return generated.map((q, idx) => ({
        id: `${skill.id}-ai-${idx + 1}`,
        checkpointId: `ai-${idx + 1}`,
        checkpointTitle: q.checkpointTitle || `${skill.name} Fundamentals`,
        question: q.question,
        options: q.options,
        correctIndex: q.correctIndex,
        explanation: q.explanation,
      }));
    }
  } catch {
    // AI unavailable - fall through to fallback template
  }

  const bCheckpoints: SkillCheckpoint[] = skill.levels?.beginner?.checkpoints || [
    { id: 'b1', title: 'Core Syntax, Environment & Fundamentals', completed: false },
    { id: 'b2', title: 'State, Logic Flow & Data Operations', completed: false },
    { id: 'b3', title: 'Error Handling, Modularity & Best Practices', completed: false },
  ];

  const questions: AssessmentQuestion[] = [];
  const count = 5;

  for (let i = 0; i < count; i++) {
    const cp = bCheckpoints[i % bCheckpoints.length];
    const cpTitle = cp?.title || `${skill.name} Fundamentals`;

    if (i === 0) {
      questions.push({
        id: `${skill.id}-q1`,
        checkpointId: cp?.id,
        checkpointTitle: cpTitle,
        question: `In ${skill.name}, what is the foundational concept behind "${cpTitle}"?`,
        options: [
          `It defines the core building blocks, execution lifecycle, and syntax standards required for predictable operation in ${skill.name}.`,
          `It is an optional third-party plug-in used exclusively for database migrations.`,
          `It requires compiling ${skill.name} into assembly instructions using custom hardware.`,
          `It executes synchronous blocking operations on the operating system kernel loop.`,
        ],
        correctIndex: 0,
        explanation: `Mastery of "${cpTitle}" establishes the fundamental architecture and predictable execution flow in ${skill.name}.`,
      });
    } else if (i === 1) {
      questions.push({
        id: `${skill.id}-q2`,
        checkpointId: cp?.id,
        checkpointTitle: cpTitle,
        question: `When implementing "${cpTitle}" in ${skill.name}, which of the following is considered an industry best practice?`,
        options: [
          `Hardcoding global state and suppressing all runtime error warnings.`,
          `Writing modular, decoupled components/functions with explicit type contracts and clear boundaries.`,
          `Disabling logging and testing directly on the production deployment.`,
          `Storing all variable data in global mutable singleton objects.`,
        ],
        correctIndex: 1,
        explanation: `In ${skill.name}, clean separation of concerns and explicit contracts avoid unexpected side effects and make code verifiable.`,
      });
    } else if (i === 2) {
      questions.push({
        id: `${skill.id}-q3`,
        checkpointId: cp?.id,
        checkpointTitle: cpTitle,
        question: `What common failure mode or bottleneck occurs when "${cpTitle}" is poorly configured in ${skill.name}?`,
        options: [
          `Uncontrolled memory leaks, unhandled exceptions, or excessive redundant recalculations.`,
          `Automatic reformatting of the host hard drive.`,
          `Immediate invalidation of the domain SSL certificate.`,
          `The CPU frequency drops to zero.`,
        ],
        correctIndex: 0,
        explanation: `Improper configuration of "${cpTitle}" typically leads to memory bloat, unhandled edge cases, or performance degradation.`,
      });
    } else if (i === 3) {
      questions.push({
        id: `${skill.id}-q4`,
        checkpointId: cp?.id,
        checkpointTitle: cpTitle,
        question: `How does ${skill.name} handle state propagation and data flow within "${cpTitle}"?`,
        options: [
          `Through arbitrary global variables accessed across thread boundaries without locks.`,
          `Through structured parameter passing, scoped variables, and explicit lifecycle hooks.`,
          `By querying external web servers over raw TCP sockets on every line of code.`,
          `By writing state directly into browser cookies.`,
        ],
        correctIndex: 1,
        explanation: `Reliable systems maintain deterministic state propagation through scoped inputs, immutable transforms, and structured data handling.`,
      });
    } else {
      questions.push({
        id: `${skill.id}-q5`,
        checkpointId: cp?.id,
        checkpointTitle: cpTitle,
        question: `Why is verifying understanding of "${cpTitle}" essential before advancing to intermediate architectures in ${skill.name}?`,
        options: [
          `Intermediate design patterns build directly upon these foundational concepts and assume fluency with core mechanics.`,
          `It is required by government regulatory bodies before compiling code.`,
          `It reduces the size of git commits by 50%.`,
          `Without it, package managers refuse to install dependencies.`,
        ],
        correctIndex: 0,
        explanation: `Advanced abstractions and architectural patterns depend on a solid mastery of beginner fundamentals and error-handling routines.`,
      });
    }
  }

  return questions;
};

/**
 * Evaluates assessment answers and returns score, pass status (>= 80%), and checkpoint breakdown.
 */
export const evaluateAssessment = (
  skill: Skill,
  questions: AssessmentQuestion[],
  answers: Record<number, number> // questionIndex -> selectedOptionIndex
): AssessmentResult => {
  let correctCount = 0;
  const breakdown: AssessmentResult['checkpointBreakdown'] = [];

  questions.forEach((q, idx) => {
    const selected = answers[idx];
    const isCorrect = selected === q.correctIndex;
    if (isCorrect) correctCount++;

    breakdown.push({
      checkpointTitle: q.checkpointTitle,
      passed: isCorrect,
      explanation: q.explanation,
    });
  });

  const totalQuestions = questions.length || 1;
  const scorePercentage = Math.round((correctCount / totalQuestions) * 100);
  const passed = scorePercentage >= 80;

  return {
    skillId: skill.id,
    skillName: skill.name,
    totalQuestions: questions.length,
    correctAnswers: correctCount,
    scorePercentage,
    passed,
    status: passed ? 'verified' : 'self-claimed',
    checkpointBreakdown: breakdown,
  };
};